# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 06:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='articles',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
