# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20170401_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='visit_num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
