# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_article_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
